package oneday;

// do not edit, derived from the London database.  run the  Cardmaker.main

public class LondonData {
public static void loadData()
{
new Line("Bakerloo","Brown",176,97,16,255,true,18,9,0,Station.brownIndex);
new Line("Central","Red",239,46,36,0,true,19,11,0,Station.redIndex);
new Line("Circle","Yellow",255,210,3,0,false,59,10,0,Station.yellowIndex);
new Line("District","Green",0,134,64,255,true,35,12,0,Station.greenIndex);
new Line("Hammersmith & City","Pink",242,133,161,0,true,22,10,0,Station.pinkIndex);
new Line("Jubilee","Gray",149,156,162,0,true,12,8,0,Station.grayIndex);
new Line("Metropolitan","Purple",152,0,93,255,true,29,10,5,Station.purpleIndex);
new Line("Northern","Black",35,31,32,255,true,26,8,0,Station.blackIndex);
new Line("Piccadilly","Blue",28,63,149,255,true,18,8,0,Station.blueIndex);
new Line("Victoria","Cerulian Blue",0,157,220,0,true,15,6,0,Station.cerulianIndex);
new Line("Waterloo & City","Aqua",134,206,188,0,true,5,5,0,Station.aquaIndex);
new Station("Aldgate","Metropolitan,Circle,Hammersmith & City,District","Aldgate-Station-Entrance.jpg",94.9,42.2,"Opened 1876","ALL-GATE","Go shopping under the stunning glass roof of Leadenhall Market, built on the site of a Roman forum and basilica. Or update your ‘cred with new clothes from Petticoat Lane Market (Sundays). Also stop here for Whitechapel Art Gallery.");
new Station("Angel","Northern","Angel-southbound.jpg",72.5,11.2,"Opened 1901","ANGE-ALL","Get cultured. This is the home of Off-West End fringe theater. Stock up on fruit and veg at the daily Chapel Market.  Or check out the waterways of the Regents Canal.");
new Station("Baker Street","Bakerloo,Metropolitan,Circle,Hammersmith & City,Jubilee","BakerStEntrance.JPG",35.6,27.0,"Opened 1863","BAY-KER","Unravel the mystery at the Sherlock Holmes’ museum, take a walk in Regent's park, or watch a match at Lord's cricket ground.");
new Station("Bank","Waterloo & City,Northern,Central","Bank_station_westbound_Central_look_east.JPG",84.5,44.0,"Opened 1898","BANK","In the heart of London's financial district. Today Britain uses Pounds and Pence, but what were Shillings and Thruppence? Find out at the Bank of England museum on Threadneedle Street");
new Station("Barbican","Metropolitan,Circle,Hammersmith & City","Barbican.jpg",78.3,32.1,"Opened 1865","BAR-be-can","Find out about prehistoric London, the Romans, the Black Death, or the Great Fire. In fact, everything you ever wanted to know about the city at the Museum of London. Or visit the Barbican Center, Europe's largest multi-arts and conference venue.");
new Station("Bayswater","District,Circle","Bayswater_Station_Exterior.jpg",13.7,45.8,"Opened 1868","BAYS-WATER","Visit Queensway St. if you need to do some shopping or want to eat Chinese, Arab or Mediterranean, or head to the nearby Portobello Market to browse its famed antiques. Walk through Kensington Gardens, whose 270 acres were once part of the grounds of Kensington Palace.");
new Station("Blackfriars","District,Circle","Blackfriars.jpg",74.3,47.1,"Opened 1870","BLACK-FRYERS","Site of a former priory, now home to many investment banks and financial companies. Sherlock Holmes was filmed in this area.  Cross over the river to visit Tate Modern.");
new Station("Bond Street","Central,Jubilee","Bond_Street_stn_Central_line_westbound.JPG",41.3,43.0,"Opened 1900","BOND (as in James)","Bring your mullah! Set in the heart of Mayfair, Bond Street is the shopping playground for the wealthy, equivalent to LA's Rodeo Drive. Claridges and the Ritz hotels are both nearby, as is the Royal Academy of Art.");
new Station("Borough","Northern","Borough_tube_station_2005-11-27.jpg",81.05,64.05,"Opened 1890","BURR-a","Known as a foodie's paradise, Borough Market is a farmers market on steroids. Come hungry! Area is also home to many restaurants and pubs. The London Dungeon, original London Bridge and the replica of Shakespeare's Globe Theatre are all nearby.");
new Station("Cannon Street","District,Circle","CannonStreet.jpg",83.5,47.2,"Opened 1884","CAN-NON","On the north side of the river, and in the heart of London's financial district. Connects to a railway terminus of the same name. Built on the site of the medieval Steelyard (from the Dutch/German Stalhof), which like other Hansa stations, was a separate walled community with its own warehouses and stores set on the river.");
new Station("Chancery Lane","Central","Chancery_Lane_stn_northeast_entrance.JPG",68.2,35.4,"Opened 1900","CHANCE-ery","The home of many of London's legal firms and of King College's Maughan Research Library. Need to buy/rent a legal or academic gown, or some other ceremonial dress? Visit Ede & Ravenscroft, London's oldest tailors.");
new Station("Charing Cross","Bakerloo,Northern","Charing_cross_london_underground.jpg",59.0,52.0,"Opened 1906","CHAIR-ring cross","Alight here to visit the art treasures of the National Gallery and see Nelson's Column in Trafalgar Square. Transfer to the railway terminus of the same name for trains to south east London and further afield into Kent and East Sussex.");
new Station("Covent Garden","Piccadilly","CoventGardenTubeStation.jpg",59.4,44.5,"Opened 1907","COV-vent garden","Alight here to watch some street theatre and wander around the eclectic shops, restaurants and bars. Learn more about the Tube at the London Transport Museum. Or perhaps some high culture at the Royal Opera House is more your thing.");
new Station("Earl's Court","District,Piccadilly","London_Train_Station.jpg",9.3,80.7,"Opened 1871 resited 1878 ","EARL's Court","Earl's Court tube (with an apostrophe) is the stop for Earls Court exhibition center. The venue hosts some 200 trade shows per year as well as music concerts. In the 60's & 70's the area was home to many Aussies and Kiwis. Famous residents have included Princess Diana, Freddie Mercury and Alfred Hitchcock.");
new Station("Edgware Road Bakerloo","Bakerloo","Edgware_Road_stn_Bakerloo.png",28.2,33.0,"Opened 1907","EDGE-ware","Edgware Road is known for its diversity and multiculturalism. In 2007, there was proposal to rename this station Church Street Market to bring an end to the confusion between this stop and its namesake station on the Circle, District and Hammersmith & City line.");
new Station("Edgware Road Circle","District,Circle,Hammersmith & City","EdgwareRdHammersmith.jpg",26.15,32.1,"Opened 1863","EDGE-ware","The station is part of the world's first underground line, Metropolitan. Edgware Road is known for its diversity and multiculturalism. This was where one of the 4 bombs went off on July 7, 2005 - the UK's equivalent to 9/11, the others being Liverpool Street, Kings Cross, and a bus at Tavistock Square.");
new Station("Elephant & Castle","Northern,Bakerloo","Elephant__Castle_stn_south_entrance.JPG",76.1,73.2,"Opened 1890","ELLA-FONT and CAR-sell","The Elephant & Castle derives its name from an inn at this location, but today refers to the general area.  Shakespeare mentions the Elephant Lodgings in 'Twelfth Night.' Visit the the Imperial War Museum, the Cumming Museum, or the Cinema Museum. Check out the local cafes, or go clubbing at the Ministry of Sound.");
new Station("Embankment","District,Circle,Bakerloo,Northern","Embankment_station.jpg",60.8,54.0,"Opened 1870","EM-bank-mont","Enjoy art festivals at the Southbank Center, visit the Hayward Gallery, or go to a play at the Royal National Theatre, The National Theatre, the Playhouse Theatre or Festival Hall, or just enjoy the scenery and amble along the Thames River Walk.");
new Station("Euston","Northern,Victoria","Euston_station_facade.jpg",52.6,18.2,"Opened 1907","Yoo-sten","Euston is the sixth busiest train station in London, providing trains to Birmingham, Manchester, Liverpool and Scotland. See the medical items of the Wellcome Collection. Or take a walk along Euston Road towards King's Cross for the British Library.");
new Station("Euston Square","Metropolitan,Circle,Hammersmith & City","Euston_Square_stn_south_entrance.JPG",51.0,22.7,"Opened 1863","Yoo-sten square","Opened in 1863 and called Gower Street, the name changed to Euston Square in 1909. See the medical items of the Wellcome Collection. See a play at the Bloomsbury Theatre. Not to be confused with Euston tube station which is just 100 yards away.");
new Station("Farringdon","Metropolitan,Circle,Hammersmith & City","Farringdon_station_exterior.jpg",73.0,32.1,"Opened 1863 resited 1865 ","FAIR-ring-don","Take time to stop here for the Clockmaker's Museum. Get up at 4am and visit Smithfield Market, one of London’s oldest wholesale markets and a favorite of restauranteurs. Also nearby is the Barbican Theatre, the Barbican Centre, and Volupte Lounge, a cabaret club.");
new Station("Gloucester Road","District,Circle,Piccadilly","GlocesterRoadTube.jpg",16.8,75.7,"Opened 1868","GLOSS-ter","Stroll around and admire the Victorian architecture of this mainly residential area. Head south to Old Brompton Road for antique shopping.");
new Station("Goodge Street","Northern","Goodge_Street_stn_entrance.JPG",51.8,32.1,"Opened 1907","like Scroodge","One of the 8 underground stations that were used as deep level air raid shelters during World War 2. A mainly commercial area of restaurants and shops - Tottenham Court Road is nearby - also home to the Hospital  for Tropical Diseases. Visit the Pollock's Toy Museum.");
new Station("Great Portland Street","Metropolitan,Circle,Hammersmith & City","Great_Portland_St_Tube_Station.jpg",45.4,26.3,"Opened 1863","great PORT-land","The famous Great Portland Street children's hospital is here, also close to Harley Street where many private doctor offices are found. Visit the Royal Institute of British Architects Gallery, or see over 300 tanks of fish at the Aquatic Design Center. This sits at the southern end of Regent’s Park.");
new Station("Green Park","Piccadilly,Victoria,Jubilee","Green_Park_Victoria_Line_train.jpg",46.2,54.9,"Opened 1906","GREEN park","On the northern end of Green Park. Visit the Royal Academy, or check out the many restaurants and bars. Take a walk south through the park to Buckingham Palace.");
new Station("High Street Kensington","District,Circle","High_Street_Kensington_station_October_2013.jpg",11.0,65.2,"Opened 1868","KEN-sing-ton","High Street Kensington is home to many upmarket shops. Visit the royal residence of Kensington Palace, birthplace of Queen Victoria and home to Princess Diana between 1981 and 1997. Listen to some music at the Royal Albert Hall, or take a daytime walk in Holland Gardens or around the Kensington Roof Gardens (which become a club/restaurant at night)");
new Station("Holborn","Central,Piccadilly","Holborn_station_Piccadilly_westbound.JPG",62.6,37.0,"Opened 1906","HO-bon or HO-bun","Explore the literary history of nearby Bloosmbury. Also home to many great restaurants, and some of London's oldest pubs. Visit the British Museum.");
new Station("Hyde Park LeftCorner","Piccadilly","Hyde_Park_Corner.jpg",39.1,61.8,"Opened 1906","HIDE-PARK corner","Gateway to London's Hyde Park. Covering 350 acres, it has 4000 trees, the large Serpentine lake for swimming and boating, meadows and ornamental flower gardens, plus tennis courts, horse trails and a children's playground. To the south is Buckingham Palace.");
new Station("King's Cross St. Pancras","Metropolitan,Circle,Hammersmith & City,Northern,Piccadilly,Victoria","Kings_Cross_St_Pancras_tube_stn_Euston_Rd_NW_entrance.JPG",59.4,15.1,"Opened 1863 resited 1941 ","sant PAN-CRAS","Want to see the Magna Carta, or read Captain R.F. Scott's last diary entry, or hear Florence Nightingale's voice?  Visit the British Library.");
new Station("Knightsbridge","Piccadilly","Knightsbridge-tube-station-sloane-street-entrance.jpg",33.0,64.0,"Opened 1906","NIGHT'S-bridge","Do some shopping at the famous Harrod's department store, or at Harvey Nichols. Visit Aspley House, home of the first Duke of Wellington, and see Wellington's Arch across the street. To the north is Hyde Park, walk into the park and along the lake to the Serpentine Gallery.");
new Station("Lambeth North","Bakerloo","Lambethnorth.jpg",67.8,67.8,"Opened 1906","LAMB-beth","Visit the Imperial War Museum, or Florence Nightingale's Museum. Good place to start your stroll along the south bank of the river Thames, heading east past the London Eye, or walk across Westminster Bridge to see the Houses of Parliament and Big Ben.");
new Station("Lancaster Gate","Central","Lancaster_Gate_stn_entrance.JPG",22.4,46.5,"Opened 1900","LAN-cass-ter","Not too far from Paddington, situated on the north west corner of Hyde Park, at the northernmost end of the Serpentine Lake. Walk south into the Park and go boating or swimming in the lake.");
new Station("Leicester Square","Piccadilly,Northern","LeicesterSquareTubeStation.jpg",56.5,47.05,"Opened 1906","LESS-ta square","An entertainment and tourist hub. Hang out at a bar, see a show or witness a red carpet premiere at one of the cinemas. Gateway to Soho, once famous as London's red light district, now one of the more fashionable parts of the city. Soho is also the heart of the capital's vibrant gay scene.");
new Station("Liverpool Street","Metropolitan,Circle,Hammersmith & City,Central","Liverpool_Street_Underground_concourse_entr.JPG",89.4,36.9,"Opened 1875 resited 1875 ","LIV-ER-pool","Visit the shops and stalls of Old Spitalfields Market. Take in a cultural event at the Bishopsgate Institute, or just admire the building. Transfer to Liverpool Street terminus for trains to further afield. Damaged during the 1993 Bishopsgate bombing, and the terrorist attacks of July 7, 2005.");
new Station("London Bridge","Northern,Jubilee","London_bridge_tube_station.jpg",86.5,58.2,"Opened 1900","LUN-DUN","Built in 53AD, London Bridge was the only bridge across the Thames until 1750. Destroyed by fire and rebuilt several times, it was famously sold and shipped to the Americans who thought they were buying Tower Bridge. Visit the London Dungeon, Borough Market, and transfer to trains to the south east.");
new Station("Mansion House","District,Circle","Mansionhouse300.jpg",80.5,46.0,"Opened 1871","MAN-shun","Visit Mansion House, the grand Georgian style Palace of the Mayor of London, open by appointment only. Or take a stroll along the north side of the Thames. Walk across the pedestrian-only Millennium Bridge (opened in 2000) to the south side of the Thames to see some art at Tate Modern.");
new Station("Marble Arch","Central","Marble_Arch_stn_eastbound_look_west.JPG",34.8,43.0,"Opened 1900","MAR-bell Arch","Located at the north east corner of Hyde Park. Marble Arch is as its name suggests a large arch made of white marble. Designed by John Nash in 1827 as a grand state entrance to Buckingham Palace, but relocated in 1851 to what is now the centre of a traffic island. Visit Speaker's LeftCorner on this edge of Hyde Park where public debate on any lawful issue is allowed.");
new Station("Marylebone","Bakerloo","Marylebone_station_entrance.JPG",31.1,27.95,"Opened 1907","MAR-li-bun or MAR-li-ben","While all closer to Baker Street Tube, the waxworks of Madame Tussaud’s is not too far away, nor are the Sherlock Holmes Museum and Regent’s Park. Connect to the youngest of London's railway termini to catch trains to the Chilterns and Birmingham.");
new Station("Monument","District,Circle","Monument_underground_station.jpg",86.5,48.5,"Opened 1884","MON-u-ment","On the northern side of the Thames near London Bridge - the bridge that was famously sold to the Americans (see London bridge tube). Climb the 311 spiral steps 202 feet up to the top of The Monument, from which the station takes its name for some great views of London.");
new Station("Moorgate","Northern,Metropolitan,Circle,Hammersmith & City","Entrance_to_underground_station_west_side_of_Moorgate_.jpg",84.5,35.2,"Opened 1865","MORE-gate","Visit the Barbican Center, Europe's largest multi-arts and conference venue. Also close to the Museum of London.");
new Station("Notting Hill Gate","Central,District,Circle","NottingHillGate3.jpg",7.5,50.6,"Opened 1868","KNOT-tingHill gate","Visit the nearby Portobello Market, or check out locations from the film Notting Hill. During the August bank holiday the streets north towards Notting Hill come alive with the sounds and tastes of the Notting Hill Carnival.");
new Station("Old Street","Northern","Old_Street_stn_northwest_entrance.JPG",85.6,23.3,"Opened 1901","OLD Street","Relatively quiet by day, the streets around Old Street tube come alive at night due to the many bars and nightclubs in the area.");
new Station("Oxford Circus","Central,Bakerloo,Victoria","Oxford_Circus_stn_Bakerloo_building.jpg",47.4,40.85,"Opened 1900","OX-fud CIR-kis","Bang in the middle of the 1.5 miles of Oxford Street, and some 300 shops including Debenhams, it’s time for some serious shopping.");
new Station("Paddington","Circle,Hammersmith & City,District,Bakerloo","Paddington_Circle-District_station.jpg",22.4,40.2,"Opened 1863","PAD-ding-ton","Visit the tube station that gave its name to Paddington Bear. Connect for trains out of town to Oxford, Bristol and into Cornwall.");
new Station("Piccadilly Circus","Bakerloo,Piccadilly","Piccadillycircus_tube_station.jpg",52.8,49.8,"Opened 1906","PICK-add-dilly CIR-kis","Not a circus at all. In the heart of London’s West End Theatre District. The buildings here were once covered in neon signs, but since toned down and now confined to one corner only. Leicester Square, the National Portrait Gallery, and the Royal Academy of Arts are all a short walk away.");
new Station("Pimlico","Victoria","PimlicoStation.jpg",52.7,84.0,"Opened 1872","PIM-lick-o","A quiet residential and business area just north of the Thames near Victoria, and only 10 minutes walk to King's Road in Chelsea. See art at Tate Britain.");
new Station("Queensway","Central","Queensway_tube_station.jpg",14.1,49.0,"Opened 1900","QUEENS-way","Located at the northwest corner of Kensington Gardens. Stroll the gardens, or visit Kensington Palace. Queensway Street itself is home to lots of Chinese, Arab and Mediterranean eateries. Portobello Market is nearby too.");
new Station("Regent's Park","Bakerloo","Regents_Park_tube_station.jpg",43.9,24.5,"Opened 1906","REE-GENT'S Park","Like Great Portland Street tube this sits at the southern end of the huge Regent's Park. Take a short walk into the park, go boating in the lake, or walk all the way across to visit the London Zoo.");
new Station("Russell Square","Piccadilly","Russell_Square_station.jpg",59.0,27.9,"Opened 1906","RUSS-el","Alight here to see the treasures of the British Museum, visit Charles Dickens’ Museum, or to visit the modern art galleries at The Horse Hospital. Also home to the art-house Renoir Cinema, and the Dominion Theatre famed for musicals. Russell Square itself is a historic green space located within the Bloomsbury district of London.");
new Station("Sloane Square","District,Circle","River_westbourne_sloane_square.jpg",36.25,79.3,"Opened 1868","Sloan","In the London area of Belgravia, Sloane Square is famed for its specialist stores and home to the Royal Court Theatre. Also stop here for contemporary art at the Saatchi Gallery. Or to visit loved ones at the Royal Hospital at Chelsea. Close to Victoria train station.");
new Station("South Kensington","District,Circle,Piccadilly","South_Kensington_station.jpg",23.6,76.5,"Opened 1868","KEN-sing-ton","Visit some of London's best museums: period costumes and history at the Victoria & Albert (the V&A), the National History Museum and the Science Museum. Or take in a concert at the Royal Albert Hall, just a short walk to the north.");
new Station("Southwark","Jubilee","Southwarktubestation.JPG",73.2,59.8,"Opened 1899","SUTH-urk","Just south of the river, a short stroll brings you to the riverfront. Here is Tate Modern (a modern art gallery housed in the former Bankside Power Station), and the rebuilt Shakespeare’s Globe (the original 16th century theatre stood just a few 100 yards away). Nearby Borough Market offers many food and drink options. Waterloo train station is just to the east.");
new Station("St. James's Park","District,Circle","BroadwayLondon.jpg",52.3,67.2,"Opened 1868","Saint JAME'S park","Take a stroll in St. James Park, or visit Westminster Abbey and the Houses of Parliament. Buckingham Palace and the Cabinet War Rooms that sheltered Winston Churchill and government during the blitz of WWII are both close by.");
new Station("St. Paul's","Central","St_Pauls_station_eastbound_look_west_refurb.JPG",78.3,41.3,"Opened 1900","Saint PAUL'S","See Sir Christopher Wren's most famous building, St. Paul's Cathedral. Built after the great fire of London, it was completed in 1707. The funerals of Lord Nelson, the Duke of Wellington and Sir Winston Churchill were conducted here, as was the wedding of Prince Charles and Lady Diana Spencer. Climb up to the dome for some of the best views of London.");
new Station("Temple","District,Circle","Templetube.jpg",67.25,47.8,"Opened 1870","TEM-pull","On the north side of the river, not too far from Covent Garden. Visit the Courtauld art galleries at historic Somerset House. Or cross Waterloo Bridge to the southside of the river to visit the Royal National Theatre and the Southbank Centre.");
new Station("Tottenham Court Road","Central,Northern","Tottenhamstation_londonunderground.jpg",54.5,39.0,"Opened 1900","TOT-num","See the national collection of science and art treasures at the British museum. Check out the consumer electronics shops for your next camera or laptop.");
new Station("Tower Hill","District,Circle","Tower_hill_entrance.jpg",93.4,49.0,"Opened 1882 resited 1884,1967","TOWER Hill","Visit (but don't get locked up) in the Her Majesty's Royal Palace and Fortress, known more informally as the Tower of London - place of death and torture and home to the crown jewels. Afterwards grab a bite in the beautiful St. Katherine's Dock area, and stroll across Tower Bridge, London's most ornate bridge across the Thames.");
new Station("Vauxhall","Victoria","Vauxhall_mainline_stn_north_building.JPG",59.4,90.1,"Opened 1871","VOX-HAUL","On the south side of the Thames. Watch some cricket at the Oval, home to the Surrey Cricket Club since it was built in 1845, and the first to host international Test cricket matches. Also near Tate Britain and the Gasworks artist galleries.");
new Station("Victoria","District,Circle,Victoria","London_Victoria_station_-14Oct2008.jpg",45.4,72.5,"Opened 1868","VICK-tor-e-a","This London train terminus is named after Britain’s longest serving monarch, Queen Victoria. Connect here for trains to England's south coast. Westminster Cathedral and Buckingham Palace are both nearby.");
new Station("Warren Street","Northern,Victoria","Warren_Street_stn_entrance.JPG",49.2,26.3,"Opened 1907","WAR-REN","Stroll around Fitzroy Square, one of the Georgian squares in London, or see a play at the Bloomsbury Theatre. Follow in the steps of George Orwell, Anthony Burgess and Dylan Thomas and stop for a pint at The Wheatsheaf pub on Rathbone Place.");
new Station("Waterloo","Waterloo & City,Bakerloo,Northern,Jubilee","Waterloo_tube_stn_Northern_southbound_look_north.JPG",67.2,61.0,"Opened 1906","WAR-TER-loo","Board the London Eye to see the city from above (spectacular at sunset), or visit the Aquarium. Enjoy the art festivals of the Southbank Centre, or a play at the Royal National Theatre. Connect to trains leaving London.");
new Station("Westminster","District,Circle,Jubilee","Westminster_station_entrance_Portcullis_House.JPG",58.9,64.0,"Opened 1868","WEST-min-sta","Attend a debate at the Houses of Parliament, site of government since 1512, and a royal palace from 1016. Set your watch to Big Ben. On Nov 5th, 1605, Guy Fawkes tried (but failed) to blow up the 'Houses,' and to this day, every Nov 5th is celebrated across the UK with bonfires and fireworks.");
new Stop("Aldgate","District",20);
new Stop("Aldgate","Hammersmith & City",11);
new Stop("Aldgate","Metropolitan",9);
new Stop("Angel","Northern",7);
new Stop("Baker Street","Bakerloo",4);
new Stop("Baker Street","Hammersmith & City",3);
new Stop("Baker Street","Jubilee",1);
new Stop("Baker Street","Metropolitan",1);
new Stop("Bank","Central",11);
new Stop("Bank","Northern",4);
new Stop("Bank","Waterloo & City",2);
new Stop("Barbican","Hammersmith & City",8);
new Stop("Barbican","Metropolitan",6);
new Stop("Bayswater","District",3);
new Stop("Blackfriars","District",15);
new Stop("Bond Street","Central",5);
new Stop("Bond Street","Jubilee",2);
new Stop("Borough","Northern",2);
new Stop("Cannon Street","District",17);
new Stop("Chancery Lane","Central",9);
new Stop("Charing Cross","Bakerloo",8);
new Stop("Charing Cross","Northern",14);
new Stop("Covent Garden","Piccadilly",9);
new Stop("Earl's Court","District",6);
new Stop("Earl's Court","Piccadilly",1);
new Stop("Edgware Road Bakerloo","Bakerloo",2);
new Stop("Edgware Road Circle","District",1);
new Stop("Edgware Road Circle","Hammersmith & City",2);
new Stop("Elephant & Castle","Bakerloo",12);
new Stop("Elephant & Castle","Northern",1);
new Stop("Embankment","Bakerloo",9);
new Stop("Embankment","District",13);
new Stop("Embankment","Northern",15);
new Stop("Euston","Northern",9);
new Stop("Euston","Victoria",2);
new Stop("Euston Square","Hammersmith & City",5);
new Stop("Euston Square","Metropolitan",3);
new Stop("Farringdon","Hammersmith & City",7);
new Stop("Farringdon","Metropolitan",5);
new Stop("Gloucester Road","District",7);
new Stop("Gloucester Road","Piccadilly",2);
new Stop("Goodge Street","Northern",11);
new Stop("Great Portland Street","Hammersmith & City",4);
new Stop("Great Portland Street","Metropolitan",2);
new Stop("Green Park","Jubilee",3);
new Stop("Green Park","Piccadilly",6);
new Stop("Green Park","Victoria",5);
new Stop("High Street Kensington","District",5);
new Stop("Holborn","Central",8);
new Stop("Holborn","Piccadilly",10);
new Stop("Hyde Park LeftCorner","Piccadilly",5);
new Stop("King's Cross St. Pancras","Hammersmith & City",6);
new Stop("King's Cross St. Pancras","Metropolitan",4);
new Stop("King's Cross St. Pancras","Northern",8);
new Stop("King's Cross St. Pancras","Piccadilly",12);
new Stop("King's Cross St. Pancras","Victoria",1);
new Stop("Knightsbridge","Piccadilly",4);
new Stop("Lambeth North","Bakerloo",11);
new Stop("Lancaster Gate","Central",3);
new Stop("Leicester Square","Northern",13);
new Stop("Leicester Square","Piccadilly",8);
new Stop("Liverpool Street","Central",12);
new Stop("Liverpool Street","Hammersmith & City",10);
new Stop("Liverpool Street","Metropolitan",8);
new Stop("London Bridge","Jubilee",7);
new Stop("London Bridge","Northern",3);
new Stop("Mansion House","District",16);
new Stop("Marble Arch","Central",4);
new Stop("Marylebone","Bakerloo",3);
new Stop("Monument","District",18);
new Stop("Moorgate","Hammersmith & City",9);
new Stop("Moorgate","Metropolitan",7);
new Stop("Moorgate","Northern",5);
new Stop("Notting Hill Gate","Central",1);
new Stop("Notting Hill Gate","District",4);
new Stop("Old Street","Northern",6);
new Stop("Oxford Circus","Bakerloo",6);
new Stop("Oxford Circus","Central",6);
new Stop("Oxford Circus","Victoria",4);
new Stop("Paddington","Bakerloo",1);
new Stop("Paddington","District",2);
new Stop("Paddington","Hammersmith & City",1);
new Stop("Piccadilly Circus","Bakerloo",7);
new Stop("Piccadilly Circus","Piccadilly",7);
new Stop("Pimlico","Victoria",7);
new Stop("Queensway","Central",2);
new Stop("Regent's Park","Bakerloo",5);
new Stop("Russell Square","Piccadilly",11);
new Stop("Sloane Square","District",9);
new Stop("South Kensington","District",8);
new Stop("South Kensington","Piccadilly",3);
new Stop("Southwark","Jubilee",6);
new Stop("St. James's Park","District",11);
new Stop("St. Paul's","Central",10);
new Stop("Temple","District",14);
new Stop("Tottenham Court Road","Central",7);
new Stop("Tottenham Court Road","Northern",12);
new Stop("Tower Hill","District",19);
new Stop("Vauxhall","Victoria",8);
new Stop("Victoria","District",10);
new Stop("Victoria","Victoria",6);
new Stop("Warren Street","Northern",10);
new Stop("Warren Street","Victoria",3);
new Stop("Waterloo","Bakerloo",10);
new Stop("Waterloo","Jubilee",5);
new Stop("Waterloo","Northern",16);
new Stop("Waterloo","Waterloo & City",1);
new Stop("Westminster","District",12);
new Stop("Westminster","Jubilee",4);
new Interchange("aldgate","circle","metropolitan","4");
new Interchange("aldgate","metropolitan","hammersmith & city","4");
new Interchange("aldgate east","district","hammersmith & city","2");
new Interchange("aldgate east","district","hammersmith & city","2");
new Interchange("aldgate east","district","metropolitan","6");
new Interchange("baker street","bakerloo","circle","8");
new Interchange("baker street","bakerloo","hammersmith & city","8");
new Interchange("baker street","bakerloo","jubilee","3");
new Interchange("baker street","bakerloo","metropolitan","3");
new Interchange("baker street","circle","hammersmith & city","2");
new Interchange("baker street","circle","jubilee","8");
new Interchange("baker street","circle","metropolitan","8");
new Interchange("baker street","hammersmith & city","jubilee","8");
new Interchange("baker street","hammersmith & city","metropolitan","5");
new Interchange("baker street","jubilee","metropolitan","3");
new Interchange("bank","central","circle","7");
new Interchange("bank","central","district","7");
new Interchange("bank","central","northern","4");
new Interchange("bank","central","waterloo & city","4.5");
new Interchange("bank","circle","northern","4");
new Interchange("bank","circle","waterloo & city","10");
new Interchange("bank","district","northern","4");
new Interchange("bank","district","waterloo & city","10");
new Interchange("bank","northern","waterloo & city","7");
new Interchange("barbican","circle","hammersmith & city","2");
new Interchange("barbican","circle","metropolitan","2");
new Interchange("barbican","hammersmith & city","metropolitan","2");
new Interchange("bond street","central","jubilee","4");
new Interchange("charing cross","bakerloo","northern","7");
new Interchange("earl's court","district","district","2");
new Interchange("earl's court","district","piccadilly","3");
new Interchange("Edgware Road Circle","district","hammersmith & city","4");
new Interchange("elephant & castle","bakerloo","northern","2");
new Interchange("embankment","bakerloo","circle","5");
new Interchange("embankment","bakerloo","district","5");
new Interchange("embankment","bakerloo","northern","5");
new Interchange("embankment","circle","district","4");
new Interchange("embankment","circle","northern","5");
new Interchange("embankment","district","northern","5");
new Interchange("euston","northern","victoria","5");
new Interchange("euston square","hammersmith & city","circle","2");
new Interchange("euston square","metropolitan","circle","2");
new Interchange("euston square","metropolitan","hammersmith & city","2");
new Interchange("farringdon","hammersmith & city","circle","4");
new Interchange("farringdon","metropolitan","circle","4");
new Interchange("farringdon","metropolitan","hammersmith & city","4");
new Interchange("gloucester road","circle","district","4");
new Interchange("gloucester road","circle","piccadilly","7");
new Interchange("gloucester road","district","piccadilly","7");
new Interchange("great portland street","circle","hammersmith & city","5");
new Interchange("great portland street","metropolitan","circle","5");
new Interchange("great portland street","metropolitan","hammersmith & city","5");
new Interchange("green park","jubilee","piccadilly","5.5");
new Interchange("green park","jubilee","victoria","4.5");
new Interchange("green park","piccadilly","victoria","4");
new Interchange("high street kensington","district","district","4");
new Interchange("holborn","central","piccadilly","6");
new Interchange("King's Cross St. Pancras","circle","metropolitan","2");
new Interchange("King's Cross St. Pancras","circle","northern","7.5");
new Interchange("King's Cross St. Pancras","circle","piccadilly","5");
new Interchange("King's Cross St. Pancras","hammersmith & city","northern","7.5");
new Interchange("King's Cross St. Pancras","hammersmith & city","piccadilly","5");
new Interchange("King's Cross St. Pancras","hammersmith & city","victoria","5");
new Interchange("King's Cross St. Pancras","metropolitan","hammersmith & city","2");
new Interchange("King's Cross St. Pancras","metropolitan","northern","7.5");
new Interchange("King's Cross St. Pancras","metropolitan","piccadilly","5");
new Interchange("King's Cross St. Pancras","metropolitan","victoria","5");
new Interchange("King's Cross St. Pancras","northern","piccadilly","2.5");
new Interchange("King's Cross St. Pancras","northern","victoria","4.5");
new Interchange("King's Cross St. Pancras","piccadilly","victoria","2");
new Interchange("leicester square","northern","piccadilly","4");
new Interchange("liverpool street","central","circle","6");
new Interchange("liverpool street","central","hammersmith & city","6");
new Interchange("liverpool street","central","metropolitan","6");
new Interchange("liverpool street","circle","hammersmith & city","4");
new Interchange("liverpool street","circle","metropolitan","4");
new Interchange("liverpool street","hammersmith & city","metropolitan","4");
new Interchange("london bridge","jubilee","northern","6");
new Interchange("mansion house","circle","district","4");
new Interchange("monument","central","circle","7");
new Interchange("monument","central","district","7");
new Interchange("monument","central","northern","4");
new Interchange("monument","central","waterloo & city","4.5");
new Interchange("monument","circle","district","4");
new Interchange("monument","circle","northern","4");
new Interchange("monument","district","northern","4");
new Interchange("monument","northern","waterloo & city","7");
new Interchange("moorgate","circle","hammersmith & city","4");
new Interchange("moorgate","circle","metropolitan","4");
new Interchange("moorgate","hammersmith & city","metropolitan","4");
new Interchange("moorgate","hammersmith & city","northern","7");
new Interchange("moorgate","metropolitan","northern","7");
new Interchange("notting hill gate","central","circle","4");
new Interchange("notting hill gate","central","district","4");
new Interchange("notting hill gate","circle","district","4");
new Interchange("oxford circus","bakerloo","central","7");
new Interchange("oxford circus","bakerloo","victoria","4");
new Interchange("oxford circus","central","victoria","4");
new Interchange("paddington","bakerloo","circle","7");
new Interchange("paddington","bakerloo","district","7");
new Interchange("paddington","bakerloo","hammersmith & city","15");
new Interchange("paddington","circle","district","4");
new Interchange("paddington","circle","hammersmith & city","13");
new Interchange("paddington","district","hammersmith & city","13");
new Interchange("piccadilly circus","bakerloo","piccadilly","3");
new Interchange("sloane square","circle","district","5");
new Interchange("south kensington","circle","district","2");
new Interchange("south kensington","circle","piccadilly","4");
new Interchange("south kensington","district","piccadilly","4");
new Interchange("temple","circle","district","4");
new Interchange("tottenham court road","central","northern","4");
new Interchange("tower hill","circle","district","4");
new Interchange("victoria","district","victoria","4");
new Interchange("warren street","northern","victoria","6");
new Interchange("waterloo","bakerloo","jubilee","6");
new Interchange("waterloo","bakerloo","northern","4");
new Interchange("waterloo","jubilee","northern","6");
new Interchange("waterloo","waterloo & city","bakerloo","5");
new Interchange("waterloo","waterloo & city","jubilee","5");
new Interchange("waterloo","waterloo & city","northern","5");
new Interchange("westminster","circle","district","4");
new Interchange("westminster","circle","jubilee","6");
new Interchange("westminster","district","jubilee","6");
 }}
