#!/bin/csh
#
# delete sufficiently old archive directories
#
set now=`date`
set months = ("Jan" "Feb" "Mar" "Apr" "May" "Jun" "Jul" "Aug" "Sep" "Oct" "Nov" "Dec")
set month = "$now[2]"
set year = "$now[6]";
#
# retain 6 months
#
set i = 6
set ri = $i
foreach m ($months)
 @ i++
 if( $i == 13) then
  set i = 1
  endif
if($m ==  $month) then

 while($ri > 0)

 set most = $months[$i]
 set nonomatch
 echo "delete from archive-$year/games-$most"
 foreach dir(archive-$year/games-$most-*.zip)
  echo $dir
  if (-e $dir) then
  echo mv $dir ../xGames/
  endif
 end

 @ ri--;
 @ i--;
 if($i == 0) @ year--
 end

 endif
end

