codename1.android.keystore=G:\\share\\projects\\boardspace-maven\\boardspacedevelop\\common\\androidCerts\\KeyChain.ks
codename1.android.keystoreAlias=androidKey
codename1.android.keystorePassword=123456
codename1.arg.and.themeMode=modern
codename1.arg.desktop.interactiveScrollbars=true
codename1.arg.desktop.titleBar=native
codename1.arg.ios.newStorageLocation=true
codename1.arg.ios.themeMode=modern
codename1.arg.java.version=17
codename1.arg.nativeTheme=modern
codename1.cssTheme=true
codename1.displayName=Develop Boardspace
codename1.icon=icon.png
codename1.ios.appid=Q5GHSKAL2F.maven.boardspace
codename1.ios.certificate=
codename1.ios.certificatePassword=
codename1.ios.debug.certificate=G:\\share\\projects\\boardspace-maven\\boardspacedevelop\\common\\iosCerts/ios-signing-asset.p12
codename1.ios.debug.certificatePassword=cn1-1788402131066-17
codename1.ios.debug.provision=G:\\share\\projects\\boardspace-maven\\boardspacedevelop\\common\\iosCerts/Boardspace-Mavin-Develop.mobileprovision
codename1.ios.provision=
codename1.ios.release.certificate=
codename1.ios.release.certificatePassword=
codename1.ios.release.provision=
codename1.j2me.nativeTheme=nbproject/nativej2me.res
codename1.kotlin=false
codename1.languageLevel=5
codename1.mainName=Develop
codename1.packageName=mav.boardspace
codename1.rim.certificatePassword=
codename1.rim.signtoolCsk=
codename1.rim.signtoolDb=
codename1.secondaryTitle=Hello World
codename1.vendor=CodenameOne
codename1.version=19.1
codename1.arg.build.cn1Version=master
codename1.arg.ios.validateProvisioningProfile=false
codename1.arg.build.incSources=1
codename1.arg.build.version=master
