#
#Fri Jul 03 15:04:55 PDT 2026
codename1.ios.release.provision=G\:\\share\\projects\\boardspace-maven\\boardspacedevelop\\common\\iosCerts\\production_provisioning_profile.mobileprovision
codename1.ios.appid=N9ZJLP5456.maven.boardspace
codename1.arg.java.version=8
codename1.arg.ios.metal=true
codename1.j2me.nativeTheme=nativej2me.res
codename1.arg.ios.interface_orientation=UIInterfaceOrientationPortrait\:UIInterfaceOrientationPortraitUpsideDown\:UIInterfaceOrientationLandscapeLeft\:UIInterfaceOrientationLandscapeRight
codename1.displayName=boardspace
codename1.arg.ios.enableproguard=false
guiResource=theme.res
codename1.android.keystoreAlias=android
codename1.ios.debug.notificationServiceExtensionProvision=G\:\\share\\projects\\boardspace-maven\\boardspacedevelop\\common\\iosCerts\\development_notification_service_extension_provisioning_profile.mobileprovision
codename1.ios.release.certificate=G\:\\share\\projects\\boardspace-maven\\boardspacedevelop\\common\\iosCerts\\appstore_certificate.p12
codename1.android.keystorePassword=androidstore
codename1.arg.codename1.arg.ios.plistInject=<key>NSAppTransportSecurity</key><dict><key>NSAllowsArbitraryLoads</key><true/></dict>
codename1.ios.provision=
codename1.arg.android.release=true
codename1.arg.ios.entitlements.multicast=true
codename1.arg.android.multidex=true
package=generated
codename1.arg.android.includeGPlayServices=false
codename1.languageLevel=5
codename1.android.keystore=G\:\\share\\projects\\ios-certificates\\androidstore.ks
codename1.vendor=CodenameOne
codename1.arg.ios.includeNullChecks=true
codename1.arg.android.permission.ACCESS_WIFI_STATE=true
codename1.ios.certificatePassword=
codename1.ios.debug.certificatePassword=biesi24R
codename1.arg.maven.codenameone-core.version=LATEST
codename1.mainName=Develop
codename1.arg.android.enableProguard=false
codename1.ios.release.certificatePassword=U3dvEkkj
libVersion=211
codename1.ios.debug.certificate=G\:\\share\\projects\\boardspace-maven\\boardspacedevelop\\common\\iosCerts\\development_certificate.p12
codename1.arg.hyp.beamId=bca0e7bf-f33f-4d47-8871-493234d9e84b
codename1.arg.android.xapplication_attr=android\:usesCleartextTraffic\="true"
codename1.arg.android.permission.ACCESS_NETWORK_STATE=true
codename1.secondaryTitle=boardspace
codename1.ios.debug.provision=G\:\\share\\projects\\boardspace-maven\\boardspacedevelop\\common\\iosCerts\\development_provisioning_profile.mobileprovision
codename1.arg.maven.codenameone-maven-plugin=7.0.55
baseClass=src/generated/StateMachineBase.java
codename1.arg.android.largeHeap=true
codename1.arg.build.incSources=1
codename1.rim.certificatePassword=
codename1.version=27.66
codename1.ios.certificate=
codename1.icon=G\:\\share\\projects\\boardspace-codename1\\icons\\boardspace-devel-maven-512x512.png
codename1.rim.signtoolCsk=
codename1.arg.android.debug=false
codename1.rim.signtoolDb=
userClass=src/userclasses/StateMachine.java
codename1.arg.ios.fileSharingEnabled=true
codename1.packageName=maven.boardspace
codename1.ios.release.notificationServiceExtensionProvision=G\:\\share\\projects\\boardspace-maven\\boardspacedevelop\\common\\iosCerts\\production_notification_service_extension_provisioning_profile.mobileprovision
codename1.arg.ios.includePush=false
