/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */
/* acconfig.h
   This file is in the public domain.

   Descriptive text for the C preprocessor macros that
   the distributed Autoconf macros can define.
   No software package will use all of them; autoheader copies the ones
   your configure.in uses into your configuration header file templates.

   The entries are in sort -df order: alphabetical, case insensitive,
   ignoring punctuation (such as underscores).  Although this order
   can split up related entries, it makes it easier to check whether
   a given entry is in the file.

   Leave the following blank line there!!  Autoheader needs it.  */


/* Define for admin levels */
/* #undef ADMINLEVELS */

/* The concatenation of the strings "GNU ", and PACKAGE.  */
#define GNU_PACKAGE "GNU nngssrv"

/* Define if the preprocessor recognizes __FUNCTION__ */
/* #undef HAVE___FUNCTION__ */

/* Define to the mail program found */
#define MAILPROGRAM ""

/* Define to the name of the distribution.  */
#define PACKAGE "nngssrv"

/* Define to 1 if ANSI function prototypes are usable.  */
/* #undef PROTOTYPES */

/* Define to 1 if termcap/terminfo is available.  */
/* #undef TERMINFO */

/* Define to 1 if using dmalloc */
/* #undef USING_DMALLOC */

/* Define to the version of the distribution.  */
#define VERSION "1.1.17"


/* Leave that blank line there!!  Autoheader needs it.
   If you're adding to this file, keep in mind:
   The entries are in sort -df order: alphabetical, case insensitive,
   ignoring punctuation (such as underscores).  */

/* admin help file dir */
#define AHELP_DIR "/home/boardspa/bin/nngs/share/nngssrv/ahelp"

/* cgames dir */
#define CGAME_DIR "/home/boardspa/bin/nngs/share/nngssrv/cgames"

/* emoticons file */
#define EMOTES_FILE "/home/boardspa/bin/nngs/share/nngssrv/emotestr"

/* find file */
#define FIND_FILE "/home/boardspa/bin/nngs/share/nngssrv/find.out"

/* games dir */
#define GAME_DIR "/home/boardspa/bin/nngs/share/nngssrv/games"

/* Define to 1 if you have the `alarm' function. */
#define HAVE_ALARM 1

/* Define to 1 if you have the <arpa/inet.h> header file. */
#define HAVE_ARPA_INET_H 1

/* Define to 1 if you have the <arpa/telnet.h> header file. */
#define HAVE_ARPA_TELNET_H 1

/* Define to 1 if you have the <crypt.h> header file. */
#define HAVE_CRYPT_H 1

/* Define to 1 if you have the <ctype.h> header file. */
#define HAVE_CTYPE_H 1

/* Define to 1 if you have the <dirent.h> header file. */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the <endian.h> header file. */
#define HAVE_ENDIAN_H 1

/* Define to 1 if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `ftruncate' function. */
#define HAVE_FTRUNCATE 1

/* Define to 1 if you have the <gdbm.h> header file. */
/* #undef HAVE_GDBM_H */

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `crypt' library (-lcrypt). */
#define HAVE_LIBCRYPT 1

/* Define to 1 if you have the `m' library (-lm). */
#define HAVE_LIBM 1

/* Define to 1 if you have the `socket' library (-lsocket). */
/* #undef HAVE_LIBSOCKET */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <ndbm.h> header file. */
/* #undef HAVE_NDBM_H */

/* Define to 1 if you have the <netdb.h> header file. */
#define HAVE_NETDB_H 1

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* Define to 1 if you have the `pclose' function. */
#define HAVE_PCLOSE 1

/* Define to 1 if you have the `popen' function. */
#define HAVE_POPEN 1

/* Define to 1 if you have the `random' function. */
#define HAVE_RANDOM 1

/* Define to 1 if you have the `setlinebuf' function. */
#define HAVE_SETLINEBUF 1

/* Define to 1 if you have the <signal.h> header file. */
#define HAVE_SIGNAL_H 1

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/socket.h> header file. */
#define HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <term.h> header file. */
/* #undef HAVE_TERM_H */

/* Define to 1 if you have the <time.h> header file. */
#define HAVE_TIME_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `usleep' function. */
#define HAVE_USLEEP 1

/* Define to 1 if you have the <utime.h> header file. */
#define HAVE_UTIME_H 1

/* Define to 1 if you have the `vsnprintf' function. */
#define HAVE_VSNPRINTF 1

/* help files directory */
#define HELP_DIR "/home/boardspa/bin/nngs/share/nngssrv/help"

/* info directory */
#define INFO_DIR "/home/boardspa/bin/nngs/share/nngssrv/info"

/* intergo executable from http://www.cwi.nl/~jansteen/intergo/ */
#define INTERGO_FILE "/home/boardspa/bin/nngs/share/nngssrv/intergo/intergo"

/* 19x19 ladder file */
#define LADDER19_FILE "/home/boardspa/bin/nngs/share/nngssrv/ladder/ladder19"

/* 9x9 ladder file */
#define LADDER9_FILE "/home/boardspa/bin/nngs/share/nngssrv/ladder/ladder9"

/* list definition dir */
#define LIST_DIR "/home/boardspa/bin/nngs/share/nngssrv/lists"

/* logfile- NO PATH! It resides in STATS_DIR */
#define LOG_FILE "logfile"

/* Define to 1 if `major', `minor', and `makedev' are declared in <mkdev.h>.
   */
/* #undef MAJOR_IN_MKDEV */

/* Define to 1 if `major', `minor', and `makedev' are declared in
   <sysmacros.h>. */
/* #undef MAJOR_IN_SYSMACROS */

/* message directory */
#define MESSAGE_DIR "/home/boardspa/bin/nngs/share/nngssrv/messages"

/* admin motd message file */
#define MESS_AMOTD "admotd"

/* login message file */
#define MESS_LOGIN "login"

/* logout message file */
#define MESS_LOGOUT "logout"

/* motd message file */
#define MESS_MOTD "motd"

/* unreg message file */
#define MESS_UNREGISTERED "unregistered"

/* welcome message file */
#define MESS_WELCOME "welcome"

/* news files dir */
#define NEWS_DIR "/home/boardspa/bin/nngs/share/nngssrv/news"

/* notes file */
#define NOTE_FILE "/home/boardspa/bin/nngs/share/nngssrv/note"

/* file */
#define NRATINGS_FILE "/home/boardspa/bin/nngs/share/nngssrv/ratdb"

/* file */
#define NRESULTS_FILE "/home/boardspa/bin/nngs/share/nngssrv/nresults"

/* Name of package */
#define PACKAGE "nngssrv"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* player dirs */
#define PLAYER_DIR "/home/boardspa/bin/nngs/share/nngssrv/players"

/* go progblem dir */
#define PROBLEM_DIR "/home/boardspa/bin/nngs/share/nngssrv/problems"

/* file */
#define RATINGS_FILE "/home/boardspa/bin/nngs/share/nngssrv/results-rated"

/* file */
#define RESULTS_FILE "/home/boardspa/bin/nngs/share/nngssrv/results"

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* cgames file */
#define STATS_CGAMES "cgames"

/* message dir */
#define STATS_DIR "/home/boardspa/bin/nngs/share/nngssrv/stats"

/* games file */
#define STATS_GAMES "games"

/* login log file */
#define STATS_LOGONS "logons"

/* messages file */
#define STATS_MESSAGES "messages"

/* rgames file */
#define STATS_RGAMES "rgames"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Version number of package */
#define VERSION "1.1.17"

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `unsigned long' if <sys/types.h> does not define. */
/* #undef ulong */
